version: "2"
run:
  tests: true
  timeout: 5m
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - contextcheck
    - copyloopvar
    - depguard
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forbidigo
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecknoinits
    - gocritic
    - goprintffuncname
    - gosec
    - govet
    - grouper
    - inamedparam
    - ineffassign
    - intrange
    - lll
    - makezero
    - misspell
    - mnd
    - nakedret
    - nestif
    - noctx
    - nonamedreturns
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - revive
    - sloglint
    - spancheck
    - staticcheck
    - tagliatelle
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          deny:
            - pkg: reflect
              desc: not allowed
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib errors package
    forbidigo:
      forbid:
        - pattern: ^print.*$
          msg: Do not commit print statements.
        - pattern: ^fmt\.Print.*$
          msg: Do not commit print statements.
        - pattern: ^log\.Print.*$
          msg: Do not commit print statements.
      analyze-types: true
    govet:
      enable-all: true
      disable:
        - fieldalignment
    lll:
      line-length: 120
    mnd:
      ignored-functions:
        - strconv.FormatInt
        - strconv.ParseInt
        - ^gofakeit\.
    revive:
      rules:
        - name: add-constant
          arguments:
            - allowStrs: "\"\""
              ignoreFuncs: os.Exit,wg.Add,make
              maxLitCount: "3"
          severity: warning
          disabled: true
        - name: argument-limit
          arguments:
            - 4
          severity: warning
          disabled: true
        - name: atomic
          severity: error
          disabled: false
        - name: banned-characters
          severity: warning
          disabled: true
        - name: bare-return
          severity: warning
          disabled: false
        - name: blank-imports
          severity: error
          disabled: false
        - name: bool-literal-in-expr
          severity: error
          disabled: false
        - name: call-to-gc
          severity: error
          disabled: false
        - name: cognitive-complexity
          arguments:
            - 7
          severity: warning
          disabled: true
        - name: comment-spacings
          severity: warning
          disabled: false
        - name: confusing-naming
          severity: warning
          disabled: false
        - name: confusing-results
          severity: warning
          disabled: false
        - name: constant-logical-expr
          severity: error
          disabled: false
        - name: context-as-argument
          arguments:
            - allowTypesBefore: "*testing.T,testing.TB"
          severity: error
          disabled: false
        - name: context-keys-type
          severity: error
          disabled: false
        - name: cyclomatic
          arguments:
            - 10
          severity: warning
          disabled: true
        - name: datarace
          severity: error
          disabled: false
        - name: deep-exit
          severity: error
          disabled: false
        - name: defer
          arguments:
            - - call-chain
              - loop
          severity: error
          disabled: false
        - name: dot-imports
          severity: error
          disabled: false
        - name: duplicated-imports
          severity: error
          disabled: false
        - name: early-return
          arguments:
            - preserveScope
          severity: error
          disabled: false
        - name: empty-block
          severity: error
          disabled: false
        - name: empty-lines
          severity: error
          disabled: false
        - name: enforce-map-style
          arguments:
            - make
          severity: error
          disabled: false
        - name: error-naming
          severity: error
          disabled: false
        - name: error-return
          severity: error
          disabled: false
        - name: error-strings
          severity: warning
          disabled: false
        - name: errorf
          severity: error
          disabled: false
        - name: exported
          arguments:
            - preserveScope
            - checkPrivateReceivers
            - sayRepetitiveInsteadOfStutters
          severity: warning
          disabled: true
        - name: file-header
          arguments:
            - This is the text that must appear at the top of source files.
          severity: warning
          disabled: true
        - name: flag-parameter
          severity: warning
          disabled: true
        - name: function-result-limit
          arguments:
            - 4
          severity: warning
          disabled: false
        - name: function-length
          arguments:
            - 10
            - 0
          severity: warning
          disabled: true
        - name: get-return
          severity: warning
          disabled: true
        - name: identical-branches
          severity: error
          disabled: false
        - name: if-return
          severity: error
          disabled: false
        - name: increment-decrement
          severity: error
          disabled: false
        - name: indent-error-flow
          arguments:
            - preserveScope
          severity: error
          disabled: false
        - name: import-alias-naming
          arguments:
            - ^[a-z][a-z0-9]{0,}$
          severity: warning
          disabled: false
        - name: imports-blocklist
          arguments:
            - reflect
            - github.com/pkg/errors
          severity: error
          disabled: true
        - name: import-shadowing
          severity: error
          disabled: false
        - name: line-length-limit
          arguments:
            - 80
          severity: warning
          disabled: true
        - name: max-public-structs
          arguments:
            - 3
          severity: warning
          disabled: true
        - name: modifies-parameter
          severity: warning
          disabled: false
        - name: modifies-value-receiver
          severity: warning
          disabled: false
        - name: nested-structs
          severity: error
          disabled: false
        - name: optimize-operands-order
          severity: warning
          disabled: false
        - name: package-comments
          severity: warning
          disabled: true
        - name: range
          severity: warning
          disabled: false
        - name: range-val-in-closure
          severity: warning
          disabled: false
        - name: range-val-address
          severity: warning
          disabled: false
        - name: receiver-naming
          severity: warning
          disabled: false
        - name: redundant-import-alias
          severity: error
          disabled: false
        - name: redefines-builtin-id
          severity: error
          disabled: false
        - name: string-of-int
          severity: warning
          disabled: false
        - name: string-format
          arguments:
            - - core.WriteError[1].Message
              - /^([^A-Z]|$)/
              - must not start with a capital letter
            - - fmt.Errorf[0]
              - /(^|[^\.!?])$/
              - must not end in punctuation
            - - panic
              - /^[^\n]*$/
              - must not contain line breaks
          severity: warning
          disabled: true
        - name: struct-tag
          arguments:
            - json,inline
            - bson,outline,gnu
          severity: warning
          disabled: true
        - name: superfluous-else
          arguments:
            - preserveScope
          severity: error
          disabled: false
        - name: time-equal
          severity: error
          disabled: false
        - name: time-naming
          severity: error
          disabled: false
        - name: var-naming
          arguments:
            - []
            - []
            - - upperCaseConst: false
          severity: error
          disabled: false
        - name: var-declaration
          severity: error
          disabled: false
        - name: unconditional-recursion
          severity: error
          disabled: false
        - name: unexported-naming
          severity: error
          disabled: false
        - name: unexported-return
          severity: error
          disabled: false
        - name: unhandled-error
          arguments:
            - fmt.Printf
            - fmt.Println
            - strings.Builder.*
            - bytes.Buffer.*
          severity: warning
          disabled: false
        - name: unnecessary-stmt
          severity: error
          disabled: false
        - name: unreachable-code
          severity: error
          disabled: false
        - name: unused-parameter
          arguments:
            - allowRegex: ^_
          severity: error
          disabled: false
        - name: unused-receiver
          arguments:
            - allowRegex: ^_
          severity: error
          disabled: true
        - name: useless-break
          severity: error
          disabled: false
        - name: waitgroup-by-value
          severity: error
          disabled: false
        - name: unchecked-type-assertion
          arguments:
            - acceptIgnoredAssertionResult: true
          severity: error
          disabled: false
        - name: use-any
          severity: error
          disabled: false
    sloglint:
      attr-only: true
    tagliatelle:
      case:
        rules:
          bun: snake
          json: camel
    testifylint:
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: _test\.go
      - path: _test\.go
        text: Do not commit print statements
      - path: _test\.go
        text: calls to log.Fatalln only in main
      - path: _test\.go
        text: calls to log.Fatal only in main
      - path: _test\.go
        text: calls to log.Fatalf only in main
      - linters:
          - lll
        source: "^//go:generate "
    paths:
      - third_party$
      - builtin$
      - examples$
      - internal/woodpecker
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
