name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      dind:
        image: docker:24.0-dind-rootless
        ports:
          - 2375:2375
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: make generate && go mod tidy && git diff --exit-code go.mod docs/ examples/
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55
      - name: Gitea 1.20 & Woodpecker 1.0
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
        env:
          GITEA_IMAGE: gitea/gitea:1.20
          WOODPECKER_IMAGE: woodpeckerci/woodpecker-server:v1.0
      - name: Forgejo 1.20 & Woodpecker 1.0
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
        env:
          GITEA_IMAGE: codeberg.org/forgejo/forgejo:1.20
          WOODPECKER_IMAGE: woodpeckerci/woodpecker-server:v1.0
