name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      dind:
        image: docker:27-dind-rootless
        ports:
          - 2375:2375
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: hashicorp/setup-terraform@v3
      - run: make generate && go mod tidy && git diff --exit-code go.mod docs/ examples/
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.2
      - name: Gitea 1.24 & Woodpecker 3.8
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
        env:
          GITEA_IMAGE: gitea/gitea:1.24
          WOODPECKER_IMAGE: woodpeckerci/woodpecker-server:v3.8.0
