name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      dind:
        image: docker:24.0-dind-rootless
        ports:
          - 2375:2375
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: make generate && go mod tidy && git diff --exit-code go.mod docs/ examples/
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
      - run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
